[project]
name = "r4c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.4",
]

[dependency-groups]
dev = [
    "django-silk>=5.3.2",
]
